requires = ["tox>=4"]
isolated_build = true
env_list = ["3.13", "3.12", "3.11", "3.10"]

[testenv]
description = "Run tests with Python {basepython}"
runner = "uv-venv-lock-runner"
commands = ["pytest", "-vv", "-n", "auto"]
