name: Testing taskiq

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'

permissions:
  actions: read
  contents: read
  pull-requests: read

jobs:
  lint:
    strategy:
      matrix:
        cmd: ["black", "ruff", "mypy"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-suffix: 3.11
          version: "latest"
          python-version: 3.11
      - name: Install deps
        run: uv sync --all-extras
      - name: Run lint check
        run: uv run pre-commit run -a ${{ matrix.cmd }}
  pytest:
    strategy:
      matrix:
        py_version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        pydantic_ver: ["<2", ">=2.5,<3"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: "${{ matrix.os }}"
    env:
      UV_SYSTEM_PYTHON: 1
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '${{ matrix.py_version }}' 
      - id: setup-uv
        name: Setup UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-suffix: ${{ matrix.py_version }}
          version: "latest"
      - name: Install deps
        run: uv sync --all-extras
      - name: Setup pydantic version
        run: uv pip install "pydantic ${{ matrix.pydantic_ver }}"
      - name: Run pytest check
        run: uv run pytest -vv -n auto --cov="taskiq" .
      - name: Generate report
        run: uv run coverage xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v5
        if: matrix.os == 'ubuntu-latest' && matrix.py_version == '3.10'
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
